In [5]:
import numpy as np

In [10]:
A = np.array([[56.0,0.0,4.4,68.0],
[1.2,104.0,52.0,8.0],
[1.8,135.0,99.0,0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [12]:
cal=A.sum(axis=0)
print(cal)


[ 59.  239.  155.4  76.9]


In [16]:
percentage=100*A/cal.reshape(1,4)
print(np.round(percentage, 2))

[[94.92  0.    2.83 88.43]
 [ 2.03 43.51 33.46 10.4 ]
 [ 3.05 56.49 63.71  1.17]]
