In [1]:
import numpy as np

In [4]:
a=np.random.randn(5)
print(a)

[-0.3385133   0.92573866  0.67001254 -0.77400246  0.46962278]


In [5]:
print(a.shape)

(5,)


In [6]:
print(a.T)

[-0.3385133   0.92573866  0.67001254 -0.77400246  0.46962278]


In [7]:
print(np.dot(a,a.T))

2.240125478858203


In [8]:
a=np.random.randn(5,1)
print(a)

[[-1.02127743]
 [ 1.01191389]
 [-0.40126537]
 [-0.7309214 ]
 [ 0.25752821]]


In [9]:
print(a.T)

[[-1.02127743  1.01191389 -0.40126537 -0.7309214   0.25752821]]


In [10]:
print(np.dot(a,a.T))

[[ 1.04300759 -1.03344482  0.40980326  0.74647353 -0.26300775]
 [-1.03344482  1.02396972 -0.406046   -0.73962951  0.26059637]
 [ 0.40980326 -0.406046    0.1610139   0.29329344 -0.10333715]
 [ 0.74647353 -0.73962951  0.29329344  0.53424609 -0.18823288]
 [-0.26300775  0.26059637 -0.10333715 -0.18823288  0.06632078]]
